// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: modelLoader.proto

#include "modelLoader.pb.h"
#include "modelLoader.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* ModelLoader_method_names[] = {
  "/ModelLoader/GetModel",
};

std::unique_ptr< ModelLoader::Stub> ModelLoader::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ModelLoader::Stub> stub(new ModelLoader::Stub(channel, options));
  return stub;
}

ModelLoader::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetModel_(ModelLoader_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::ModelReply>* ModelLoader::Stub::GetModelRaw(::grpc::ClientContext* context, const ::ModelRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::ModelReply>::Create(channel_.get(), rpcmethod_GetModel_, context, request);
}

void ModelLoader::Stub::async::GetModel(::grpc::ClientContext* context, const ::ModelRequest* request, ::grpc::ClientReadReactor< ::ModelReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::ModelReply>::Create(stub_->channel_.get(), stub_->rpcmethod_GetModel_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::ModelReply>* ModelLoader::Stub::AsyncGetModelRaw(::grpc::ClientContext* context, const ::ModelRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ModelReply>::Create(channel_.get(), cq, rpcmethod_GetModel_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::ModelReply>* ModelLoader::Stub::PrepareAsyncGetModelRaw(::grpc::ClientContext* context, const ::ModelRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::ModelReply>::Create(channel_.get(), cq, rpcmethod_GetModel_, context, request, false, nullptr);
}

ModelLoader::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ModelLoader_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ModelLoader::Service, ::ModelRequest, ::ModelReply>(
          [](ModelLoader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ModelRequest* req,
             ::grpc::ServerWriter<::ModelReply>* writer) {
               return service->GetModel(ctx, req, writer);
             }, this)));
}

ModelLoader::Service::~Service() {
}

::grpc::Status ModelLoader::Service::GetModel(::grpc::ServerContext* context, const ::ModelRequest* request, ::grpc::ServerWriter< ::ModelReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


